### PR TITLE
Added broken namespace field for Kubernetes Deployment Target

### PR DESCRIPTION
**Pull request by jerckov**

### CODE REVIEW

**Comment by TomPeters** [comment]
Hi @jerckov, thanks for contributing!

Just to keep you updated: PRs against this repo are currently on hold and should hopefully resume within January.

**Comment by jerckov** [comment]
Hi @TomPeters ! Cool, looking forward!

**Comment by peter-dolkens** [comment]
Any update on the status of these @TomPeters? It looked like you guys were working on getting included by terraform - is that still in progress, or on hold too?

**Comment by TomPeters** [comment]
I'll defer that question to @droyad who might have more context than me

**Pull request merged**
